[package]
name = "rsh-crate"
version = "0.2.2"
edition = "2024"
license = "GPL-2.0-only"
description = "A simple shell written in rust, build for educational purpose. My goal is to learn more about rust and how interpreters work under the hood."
repository = "https://github.com/Nattakit92/rsh"
readme = "readme.md"

[[bin]]
name = "rsh"
path = "src/main.rs"

[dependencies]
termios = "0.3.3"
